<?php

namespace AppBundle\Repository;

/**
 * PredictiveStuffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredictiveStuffRepository extends \Doctrine\ORM\EntityRepository
{
}
