<?php

namespace AppBundle\Repository;

/**
 * StuffBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StuffBasketRepository extends \Doctrine\ORM\EntityRepository
{
}
